[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CIDS-Sim"
authors = [{name = "Aulia Arif Wardana", email = "aulia.wardana@pwr.edu.pl"}]
dynamic = ["1.0.0", "Simulator for CIDS based on Federated Learning"]
